name: polkadot_plugins_example
description: polkawallet_plugins_example.

publish_to: "none"

version: 0.0.1+11

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  polkadot_plugins:
    path: ../
  hooks_riverpod: ^1.0.0

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.15.0+1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
