name: polkadot_plugins
description: The kusama/polkadot network flutter plugin for polkawallet app.
version: 0.3.6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  charts_flutter: ">=0.11.0 <1.0.0"
  dartx: ^0.7.1
  encrypt: ^5.0.1
  http: ">=0.13.3"
  get_storage: ^2.0.3
  flutter_svg: ">=0.23.0 <1.0.0"
  json_annotation: ">=4.3.0 <5.0.0"
  permission_handler: ^7.2.0
  dropdown_search: ^0.6.3
  url_launcher: ^6.0.4
  hooks_riverpod: ^1.0.0
  intl: ^0.17.0
  webview_flutter: ">=2.0.0"
  flutter_inappwebview: ">=5.0.0"
  shared_preferences: ^2.0.7
  aes_ecb_pkcs5_flutter: ^0.1.2
  convert: ^3.0.1
  jaguar: ^3.0.12
  jaguar_flutter_asset: ^3.0.0
  qr_flutter: ^4.0.0
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.1
  # json_serializable: ">6.0.0 <7.0.0"
  build_runner: ">=2.0.0 <3.0.0"
  # freezed: ">=0.15.0 <0.16.0"
  freezed: ^0.15.0+1

flutter:
  assets:
    - assets/images/public/
    - assets/images/staking/
    - assets/images/gov/
    - assets/images/tokens/
    - js_api/dist/main.js
    - js_as_extension/dist/main.js
